package com.makatizen.makahanap.utils.enums;

public enum Categories {
    MOBILE_PHONE, LAPTOP, SCHOOL_SUPPLIES, ID, WALLET, UMBRELLA, BAG, KEYS,
    ART, BEAUTY_ACCESSORIES, BOOKS, CLOTHES, PAPER_WORKS, BANK_CARDS, JEWELRY, eREADERS, PC_ACCESSORIES, PHOTOGRAPHY_EQUIPMENT, MOBILE_PHONE_ACCESSORIES, SPORTS_EQUIPMENT, OTHERS
}
